<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<UseWPF>true</UseWPF>
		<EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Kamishibai.Hosting" Version="2.0.0" />
		<PackageReference Include="Wpf.Extensions.Hosting">
		  <Version>1.1.2</Version>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AdventureWorks.Purchasing.View\AdventureWorks.Purchasing.View.csproj" />
	</ItemGroup>

</Project>