<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Kamishibai.View" />
		<PackageReference Include="MahApps.Metro.IconPacks.FontAwesome">
		  <Version>5.0.0</Version>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AdventureWorks.Purchasing.ViewModel\AdventureWorks.Purchasing.ViewModel.csproj" />
		<ProjectReference Include="..\AdventureWorks.Purchasing\AdventureWorks.Purchasing.csproj" />
	</ItemGroup>

</Project>
